<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocalitesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $localites = array(
            array('id' => '1', 'commune_id' => '22', 'npa' => '2942', 'designation' => 'Alle'),
            array('id' => '2', 'commune_id' => '66', 'npa' => '2954', 'designation' => 'Asuel'),
            array('id' => '3', 'commune_id' => '65', 'npa' => '2854', 'designation' => 'Bassecourt'),
            array('id' => '4', 'commune_id' => '23', 'npa' => '2935', 'designation' => 'Beurnevésin'),
            array('id' => '5', 'commune_id' => '2', 'npa' => '2856', 'designation' => 'Boécourt'),
            array('id' => '6', 'commune_id' => '57', 'npa' => '2926', 'designation' => 'Boncourt'),
            array('id' => '7', 'commune_id' => '24', 'npa' => '2944', 'designation' => 'Bonfol'),
            array('id' => '8', 'commune_id' => '17', 'npa' => '2803', 'designation' => 'Bourrignon'),
            array('id' => '9', 'commune_id' => '50', 'npa' => '2904', 'designation' => 'Bressaucourt'),
            array('id' => '10', 'commune_id' => '59', 'npa' => '2925', 'designation' => 'Buix'),
            array('id' => '11', 'commune_id' => '30', 'npa' => '2915', 'designation' => 'Bure'),
            array('id' => '12', 'commune_id' => '66', 'npa' => '2947', 'designation' => 'Charmoille'),
            array('id' => '13', 'commune_id' => '10', 'npa' => '2843', 'designation' => 'Châtillon'),
            array('id' => '14', 'commune_id' => '36', 'npa' => '2345', 'designation' => 'La Chaux-des-Breuleux'),
            array('id' => '15', 'commune_id' => '67', 'npa' => '2906', 'designation' => 'Chevenez'),
            array('id' => '16', 'commune_id' => '9', 'npa' => '2830', 'designation' => 'Choindez'),
            array('id' => '17', 'commune_id' => '25', 'npa' => '2932', 'designation' => 'Coeuve'),
            array('id' => '18', 'commune_id' => '61', 'npa' => '2826', 'designation' => 'Corban'),
            array('id' => '19', 'commune_id' => '64', 'npa' => '2952', 'designation' => 'Cornol'),
            array('id' => '20', 'commune_id' => '29', 'npa' => '2823', 'designation' => 'Courcelon'),
            array('id' => '21', 'commune_id' => '47', 'npa' => '2825', 'designation' => 'Courchapoix'),
            array('id' => '22', 'commune_id' => '58', 'npa' => '2922', 'designation' => 'Courchavon'),
            array('id' => '23', 'commune_id' => '65', 'npa' => '2853', 'designation' => 'Courfaivre'),
            array('id' => '24', 'commune_id' => '63', 'npa' => '2950', 'designation' => 'Courgenay'),
            array('id' => '25', 'commune_id' => '9', 'npa' => '2830', 'designation' => 'Courrendlin'),
            array('id' => '26', 'commune_id' => '29', 'npa' => '2822', 'designation' => 'Courroux'),
            array('id' => '27', 'commune_id' => NULL, 'npa' => '2905', 'designation' => 'Courtedoux'),
            array('id' => '28', 'commune_id' => '59', 'npa' => '2923', 'designation' => 'Courtemaîche'),
            array('id' => '29', 'commune_id' => '63', 'npa' => '2950', 'designation' => 'Courtemautruy'),
            array('id' => '30', 'commune_id' => '8', 'npa' => '2852', 'designation' => 'Courtételle'),
            array('id' => '31', 'commune_id' => '26', 'npa' => '2933', 'designation' => 'Damphreux'),
            array('id' => '32', 'commune_id' => NULL, 'npa' => '2933', 'designation' => 'Damphreux-Lugnez'),
            array('id' => '33', 'commune_id' => '67', 'npa' => '2914', 'designation' => 'Damvant'),
            array('id' => '34', 'commune_id' => '48', 'npa' => '2800', 'designation' => 'Delémont'),
            array('id' => '35', 'commune_id' => '21', 'npa' => '2802', 'designation' => 'Develier'),
            array('id' => '36', 'commune_id' => '18', 'npa' => '2813', 'designation' => 'Ederswiler'),
            array('id' => '37', 'commune_id' => '43', 'npa' => '2885', 'designation' => 'Epauvillers'),
            array('id' => '38', 'commune_id' => '43', 'npa' => '2886', 'designation' => 'Epiquerez'),
            array('id' => '39', 'commune_id' => NULL, 'npa' => '2916', 'designation' => 'Fahy'),
            array('id' => '40', 'commune_id' => '50', 'npa' => '2902', 'designation' => 'Fontenais'),
            array('id' => '41', 'commune_id' => NULL, 'npa' => '2718', 'designation' => 'Fornet-Dessus'),
            array('id' => '42', 'commune_id' => '66', 'npa' => '2953', 'designation' => 'Fregiécourt'),
            array('id' => '43', 'commune_id' => '66', 'npa' => '2953', 'designation' => 'Fregiécourt-Pleujouse'),
            array('id' => '44', 'commune_id' => '65', 'npa' => '2855', 'designation' => 'Glovelier'),
            array('id' => '45', 'commune_id' => '40', 'npa' => '2354', 'designation' => 'Goumois'),
            array('id' => '46', 'commune_id' => NULL, 'npa' => '2908', 'designation' => 'Grandfontaine'),
            array('id' => '47', 'commune_id' => NULL, 'npa' => '2718', 'designation' => 'Lajoux JU'),
            array('id' => '48', 'commune_id' => '37', 'npa' => '2360', 'designation' => 'Le Bémont JU'),
            array('id' => '49', 'commune_id' => '39', 'npa' => '2336', 'designation' => 'Le Boéchet'),
            array('id' => '50', 'commune_id' => '42', 'npa' => '2345', 'designation' => 'Le Cerneux-Veusil'),
            array('id' => '51', 'commune_id' => '38', 'npa' => '2340', 'designation' => 'Le Noirmont'),
            array('id' => '52', 'commune_id' => '42', 'npa' => '2345', 'designation' => 'Le Peuchapatte'),
            array('id' => '53', 'commune_id' => NULL, 'npa' => '2714', 'designation' => 'Le Prédame'),
            array('id' => '54', 'commune_id' => '39', 'npa' => '2336', 'designation' => 'Les Bois'),
            array('id' => '55', 'commune_id' => '41', 'npa' => '2345', 'designation' => 'Les Breuleux'),
            array('id' => '56', 'commune_id' => '42', 'npa' => '2338', 'designation' => 'Les Emibois'),
            array('id' => '57', 'commune_id' => NULL, 'npa' => '2363', 'designation' => 'Les Enfers'),
            array('id' => '58', 'commune_id' => NULL, 'npa' => '2714', 'designation' => 'Les Genevez JU'),
            array('id' => '59', 'commune_id' => '40', 'npa' => '2353', 'designation' => 'Les Pommerats'),
            array('id' => '60', 'commune_id' => '15', 'npa' => '2807', 'designation' => 'Lucelle'),
            array('id' => '61', 'commune_id' => '27', 'npa' => '2933', 'designation' => 'Lugnez'),
            array('id' => '62', 'commune_id' => '62', 'npa' => '2827', 'designation' => 'Mervelier'),
            array('id' => '63', 'commune_id' => '16', 'npa' => '2806', 'designation' => 'Mettembert'),
            array('id' => '64', 'commune_id' => '66', 'npa' => '2946', 'designation' => 'Miécourt'),
            array('id' => '65', 'commune_id' => '2', 'npa' => '2857', 'designation' => 'Montavon'),
            array('id' => '66', 'commune_id' => '43', 'npa' => '2884', 'designation' => 'Montenol'),
            array('id' => '67', 'commune_id' => '68', 'npa' => '2362', 'designation' => 'Montfaucon'),
            array('id' => '68', 'commune_id' => '68', 'npa' => '2362', 'designation' => 'Montfavergier'),
            array('id' => '69', 'commune_id' => '59', 'npa' => '2924', 'designation' => 'Montignez'),
            array('id' => '70', 'commune_id' => '43', 'npa' => '2883', 'designation' => 'Montmelon'),
            array('id' => '71', 'commune_id' => '60', 'npa' => '2828', 'designation' => 'Montsevelier'),
            array('id' => '72', 'commune_id' => '20', 'npa' => '2812', 'designation' => 'Movelier'),
            array('id' => '73', 'commune_id' => '42', 'npa' => '2338', 'designation' => 'Muriaux'),
            array('id' => '74', 'commune_id' => '43', 'npa' => '2889', 'designation' => 'Ocourt'),
            array('id' => '75', 'commune_id' => '15', 'npa' => '2807', 'designation' => 'Pleigne'),
            array('id' => '76', 'commune_id' => '66', 'npa' => '2953', 'designation' => 'Pleujouse'),
            array('id' => '77', 'commune_id' => NULL, 'npa' => '2900', 'designation' => 'Porrentruy'),
            array('id' => '78', 'commune_id' => '12', 'npa' => '2832', 'designation' => 'Rebeuvelier'),
            array('id' => '79', 'commune_id' => '67', 'npa' => '2912', 'designation' => 'Réclère'),
            array('id' => '80', 'commune_id' => '67', 'npa' => '2912', 'designation' => 'Réclère-Roche-d\'Or'),
            array('id' => '81', 'commune_id' => '67', 'npa' => '2912', 'designation' => 'Roche-d\'Or'),
            array('id' => '82', 'commune_id' => NULL, 'npa' => '2907', 'designation' => 'Rocourt'),
            array('id' => '83', 'commune_id' => '11', 'npa' => '2842', 'designation' => 'Rossemaison'),
            array('id' => '84', 'commune_id' => '40', 'npa' => '2350', 'designation' => 'Saignelégier'),
            array('id' => '85', 'commune_id' => '5', 'npa' => '2873', 'designation' => 'Saulcy'),
            array('id' => '86', 'commune_id' => '43', 'npa' => '2888', 'designation' => 'Seleute'),
            array('id' => '87', 'commune_id' => '2', 'npa' => '2857', 'designation' => 'Séprais'),
            array('id' => '88', 'commune_id' => '44', 'npa' => '2887', 'designation' => 'Soubey'),
            array('id' => '89', 'commune_id' => '65', 'npa' => '2864', 'designation' => 'Soulce'),
            array('id' => '90', 'commune_id' => '14', 'npa' => '2805', 'designation' => 'Soyhières'),
            array('id' => '91', 'commune_id' => NULL, 'npa' => '2364', 'designation' => 'St-Brais'),
            array('id' => '92', 'commune_id' => '43', 'npa' => '2882', 'designation' => 'St-Ursanne'),
            array('id' => '93', 'commune_id' => '65', 'npa' => '2863', 'designation' => 'Undervelier'),
            array('id' => '94', 'commune_id' => '13', 'npa' => '2830', 'designation' => 'Vellerat'),
            array('id' => '95', 'commune_id' => '28', 'npa' => '2943', 'designation' => 'Vendlincourt'),
            array('id' => '96', 'commune_id' => '60', 'npa' => '2829', 'designation' => 'Vermes'),
            array('id' => '97', 'commune_id' => '60', 'npa' => '2824', 'designation' => 'Vicques'),
            array('id' => '98', 'commune_id' => '50', 'npa' => '2903', 'designation' => 'Villars-sur-Fontenais'),
            array('id' => '99', 'commune_id' => NULL, 'npa' => '', 'designation' => '-'),
            array('id' => '100', 'commune_id' => '31', 'npa' => '2053', 'designation' => 'Cernier'),
            array('id' => '101', 'commune_id' => '35', 'npa' => '2054', 'designation' => 'Chézard-St-Martin'),
            array('id' => '102', 'commune_id' => '31', 'npa' => '2056', 'designation' => 'Dombresson'),
            array('id' => '103', 'commune_id' => '33', 'npa' => '2052', 'designation' => 'Fontainemelon'),
            array('id' => '104', 'commune_id' => '34', 'npa' => '2046', 'designation' => 'Fontaines NE'),
            array('id' => '105', 'commune_id' => '32', 'npa' => '2208', 'designation' => 'Les Hauts-Geneveys'),
            array('id' => '106', 'commune_id' => '35', 'npa' => '2054', 'designation' => 'Les Vieux-Prés'),
            array('id' => '107', 'commune_id' => NULL, 'npa' => '2108', 'designation' => 'Couvet'),
            array('id' => '108', 'commune_id' => NULL, 'npa' => '2525', 'designation' => 'Le Landeron'),
            array('id' => '109', 'commune_id' => NULL, 'npa' => '2000', 'designation' => 'Neuchâtel'),
            array('id' => '110', 'commune_id' => NULL, 'npa' => '2300', 'designation' => 'La Chaux-de-fonds'),
            array('id' => '111', 'commune_id' => NULL, 'npa' => '2207', 'designation' => 'Coffrane'),
            array('id' => '113', 'commune_id' => NULL, 'npa' => '2057', 'designation' => 'Villiers'),
            array('id' => '114', 'commune_id' => NULL, 'npa' => '2043', 'designation' => 'Boudevilliers'),
            array('id' => '115', 'commune_id' => NULL, 'npa' => '2065', 'designation' => 'Savagnier'),
            array('id' => '116', 'commune_id' => NULL, 'npa' => '2058', 'designation' => 'Le Pâquier NE'),
            array('id' => '117', 'commune_id' => NULL, 'npa' => '2063', 'designation' => 'Vilars'),
            array('id' => '118', 'commune_id' => NULL, 'npa' => '2063', 'designation' => 'Saules NE'),
            array('id' => '119', 'commune_id' => NULL, 'npa' => '2042', 'designation' => 'Valangin'),
            array('id' => '120', 'commune_id' => NULL, 'npa' => '2206', 'designation' => 'Les Geneveys-s-Coffrane'),
            array('id' => '121', 'commune_id' => NULL, 'npa' => '2205', 'designation' => 'Montmollin'),
            array('id' => '122', 'commune_id' => NULL, 'npa' => '2063', 'designation' => 'Fenin'),
            array('id' => '112', 'commune_id' => NULL, 'npa' => '2063', 'designation' => 'Engollon'),
            array('id' => '123', 'commune_id' => NULL, 'npa' => '2720', 'designation' => 'Tramelan'),
            array('id' => '124', 'commune_id' => NULL, 'npa' => '2710', 'designation' => 'Tavannes'),
            array('id' => '125', 'commune_id' => '54', 'npa' => '2713', 'designation' => 'Bellelay'),
            array('id' => '126', 'commune_id' => '51', 'npa' => '2715', 'designation' => 'Châtelat'),
            array('id' => '127', 'commune_id' => '51', 'npa' => '2717', 'designation' => 'Fornet-Dessous'),
            array('id' => '128', 'commune_id' => '54', 'npa' => '2712', 'designation' => 'Le Fuet'),
            array('id' => '129', 'commune_id' => '56', 'npa' => '2748', 'designation' => 'Les Ecorcheresses'),
            array('id' => '130', 'commune_id' => '52', 'npa' => '2715', 'designation' => 'Monible'),
            array('id' => '131', 'commune_id' => '53', 'npa' => '2717', 'designation' => 'Rebévelier'),
            array('id' => '132', 'commune_id' => '54', 'npa' => '2732', 'designation' => 'Saicourt'),
            array('id' => '133', 'commune_id' => '55', 'npa' => '2716', 'designation' => 'Sornetan'),
            array('id' => '134', 'commune_id' => '56', 'npa' => '2748', 'designation' => 'Souboz'),
            array('id' => '135', 'commune_id' => NULL, 'npa' => '2500', 'designation' => 'Bienne'),
            array('id' => '136', 'commune_id' => NULL, 'npa' => '3294', 'designation' => 'Büren an der Aare'),
            array('id' => '137', 'commune_id' => NULL, 'npa' => '2606', 'designation' => 'Corgémont'),
            array('id' => '138', 'commune_id' => NULL, 'npa' => '2738', 'designation' => 'Court '),
            array('id' => '139', 'commune_id' => NULL, 'npa' => '2608', 'designation' => 'Courtelary'),
            array('id' => '140', 'commune_id' => NULL, 'npa' => '2735', 'designation' => 'Malleray'),
            array('id' => '141', 'commune_id' => NULL, 'npa' => '2740', 'designation' => 'Moutier'),
            array('id' => '142', 'commune_id' => NULL, 'npa' => '2534', 'designation' => 'Orvin'),
            array('id' => '143', 'commune_id' => NULL, 'npa' => '2603', 'designation' => 'Péry'),
            array('id' => '144', 'commune_id' => NULL, 'npa' => '2605', 'designation' => 'Sonceboz'),
            array('id' => '145', 'commune_id' => NULL, 'npa' => '2610', 'designation' => 'St-Imier'),
            array('id' => '146', 'commune_id' => '69', 'npa' => '4710', 'designation' => 'Balsthal'),
            array('id' => '147', 'commune_id' => '60', 'npa' => '2829', 'designation' => 'Envelier'),
            array('id' => '148', 'commune_id' => NULL, 'npa' => '25150', 'designation' => 'Goux-Lès-Dambelin'),
            array('id' => '149', 'commune_id' => NULL, 'npa' => '2523', 'designation' => 'Lignières NE'),
            array('id' => '150', 'commune_id' => NULL, 'npa' => '2827', 'designation' => 'La Scheulte'),
        );

        foreach ($localites as $localite) {
            DB::table('localites')->insert($localite);
        }
    }
}
